# Generated by Django 5.0.1 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avearge_rating',
            field=models.FloatField(default=0),
        ),
    ]
